### PR TITLE
docs(readme): add nixvim example

### PR DESCRIPTION
**Pull request by HeitorAugustoLN**
Also improved consistency of the examples formatting

### CODE REVIEW

**Review by mrcjkb — CHANGES_REQUESTED** [review]
Hey 👋 

thanks for the PR. As the NixVim interface could change, it would be best to just link to the NixVim docs.

**Comment by HeitorAugustoLN** [comment]
> As the NixVim interface could change, it would be best to just link to the NixVim docs.

About that, I don't think it really will change since I think it is in a good state right now, lazyLoad.settings is just a freeform settings of the lazy-loading provider,  which is probably the best solution. Also if it changes I can update it. But I don't see any problems in linking it to the nixvim docs, if you really want to.

**Comment by mrcjkb** [comment]
Sure, we can add the examples, but we should definitely link to the NixVim docs with a note like 

> [!NOTE]
>
> You can find up-to-date NixVim documentation for lazy-loading with lz.n here.

**Comment by mrcjkb** [comment]
The CI failure is probably markdownlint.

**Comment by HeitorAugustoLN** [comment]
> Sure, we can add the examples, but we should definitely link to the NixVim docs with a note like
> 
> Note
> 
> You can find up-to-date NixVim documentation for lazy-loading with lz.n here.

Got it.

**Comment by mrcjkb** [comment]
thanks 🙏 

one more thing I just realised. The NixVim nixos/home-manager examples look almost identical. 
I'd suggest just a single NixVim example. Home-manager users will likely know how to enable NixVim.

**Comment by HeitorAugustoLN** [comment]
> one more thing I just realised. The NixVim nixos/home-manager examples look almost identical.
I'd suggest just a single NixVim example. Home-manager users will likely know how to enable NixVim.

Done

**Review by mrcjkb — APPROVED** [review]

**Pull request merged**
